name: Publish to AWS CodeArtifact

on:
  workflow_run:
    workflows: ["Release and Publish"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  publish-codeartifact:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: npm ci

      - name: Verify package can be built
        run: npm pack --dry-run

      - name: Configure CodeArtifact registry
        run: |
          aws codeartifact login --tool npm \
            --domain ${{ secrets.CODEARTIFACT_DOMAIN }} \
            --domain-owner ${{ secrets.CODEARTIFACT_DOMAIN_OWNER }} \
            --repository ${{ secrets.CODEARTIFACT_REPOSITORY }}

      - name: Publish to AWS CodeArtifact
        run: npm publish

      - name: Verify publication
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "✅ Successfully published @axity/cordova-plugin-pushiomanager@$VERSION to AWS CodeArtifact"

      - name: Clean up .npmrc
        if: always()
        run: rm -f .npmrc
